### PR TITLE
Moved writing_guides to "textile" markdown file

### PR DESCRIPTION
**Pull request by Nightblade**
and cleaned up the formatting.

### CODE REVIEW

**Comment by tekkub** [comment]
Thanks, but markdown is kinda my preferred format these days.  These files used to be textile, I changed them, well, some 4 years ago.

**Comment by Nightblade** [comment]
Naww :<

But what about the (non-existant?) table formatting?

**Comment by tekkub** [comment]
Merf, that would be because github's markdown parser changed.  God damnit.

**Comment by Nightblade** [comment]
Doh.  Is there a new syntax?  I didn't notice _any_ syntax for table markdown.

**Comment by tekkub** [comment]
Markdown "proper" doesn't have table syntax, but "extended" markdown does.

**Comment by Nightblade** [comment]
Ok.  Example?  :)

**Pull request closed without merging**
